language: python

python:
  -3.6
  -3.7
  
before_install:
  -python --version
  -pip3 install -U pip
  -pip3 install -U pytest
  -pip3 install -U git
  -pip3 install git+https://github.com/mwsu-csmp/curriculum.git
  
install:
  -pip3 install ".[test]" .
script: pytest
  
