language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"
  
before_install:
  - python --version
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install git+https://github.com/mwsu-csmp/curriculum.git
  
script:
  - pytest
  
